#!/bin/bash

export PATH=$HOME/.volta/bin:$PATH

# find the file prettier is trying to prettify
file=${BASH_ARGV[0]:="."}
dir="$(dirname "${file}")"

# default to global prettier
prettier=`which prettier`
has_config=false

# iterate upward through parent directories looking for prettier binary and config
while [[ "$dir" != "" ]]; do
    _prettier="${dir}/node_modules/.bin/prettier"

    [ -e _prettier ] && prettier="${_prettier}"
    [ -e "${dir}/.prettierrc" ] && has_config=true

    dir=${dir%/*}
done

if [ "$has_config" = true ]; then
    exec $prettier "$@"
else
    # prettier config not found, don't prettify and instead act as a pass-through
    exec cat <&0
fi
